server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    stream:
      username: guest
      password: guest
    port: 5672
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/projects/moiza-msa/configuration
#        git:
#          uri:
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
